---
- name: create initial flavors
  os_nova_flavor:
    name: "{{ item.name }}"
    ram: "{{ item.ram }}"
    vcpus: "{{ item.vcpu }}"
    disk: "{{ item.disk }}"
  with_items: "{{ nova_flavors }}"
  tags:
    - flavor

- name: ensure image download folder
  file:
    path: "{{ image_download_folder }}"
    state: directory
    recurse: true
  tags:
    - image

- name: check local images
  stat:
    path: "{{ image_download_folder }}/{{ item.download_url | basename }}"
  register: check_local_images
  with_items: "{{ images }}"
  tags:
    - image

- name: download the images
  get_url:
    url: "{{ item.item.download_url }}"
    dest: "{{ image_download_folder }}/{{ item.item.download_url | basename }}"
  when:
    - not item.stat.exists
  with_items: "{{ check_local_images.results }}"
  tags:
    - image

- name: upload glance image
  os_image:
    name: "{{ item.name }}"
    container_format: "{{ item.container_format | default('bare') }}"
    disk_format: "{{ item.disk_format | default('qcow2') }}"
    filename: "{{ image_download_folder }}/{{ item.download_url | basename }}"
    is_public: true
    properties:
      hw_scsi_model: "{{ 'virtio-scsi' if item.enable_discard else omit }}"
      hw_disk_bus: "{{ 'scsi' if item.enable_discard else omit }}"
  with_items: "{{ images }}"
  tags:
    - image

# vim:ft=yaml
